### ISSUE TITLE
Can you help me build custom chromium with a donnation

### ISSUE THREAD

**Issue by GenderAPI** [kiwibrowser/android#114] opened 2019-10-14 07:47 UTC
i want to build an android chromium with an extension installed by default from google webstore

is it possbile

and if yes can you help me if i donate your project

**Comment by KaKi87** [comment] 2021-07-23 13:55
Duplicate of kiwibrowser/src.next#123

**Closed by KaKi87** 2021-07-23 13:55 UTC
Labels: triage

**Comment by KaKi87** [comment] 2021-07-23 23:46
Covered by kiwibrowser/src#52
