### ISSUE TITLE
Picture-in-picture option?

### ISSUE THREAD

**Issue by ericpa06** [kiwibrowser/android#56] opened 2019-05-08 07:28 UTC
So, I couldn't find any topic on this issue, if there is, please delete this one. But I recently came across kiwi browser and I just loved it. Although apparently there isn't any picture-in-picture option, like, when you start to play a video and go to another app, or even another tab of kiwi browser, although the video doesn't stop playing and you can hear it in the background, you don't have any option to have a little floating window with the minimized video running on it, such as it happens in Samsung Browser or even Chrome itself.

Is this something that you guys intend to add it? Because aside from that you folks pretty much created the perfect android browser, this is the only thing missing, it would be awesome if it was implemented. Anyway, thank you very much.

**Comment by KaKi87** [comment] 2021-07-23 14:53
Duplicate of #55

**Closed by KaKi87** 2021-07-23 14:53 UTC
