### ISSUE TITLE
[Extension] YouTube Background Playback

### ISSUE THREAD

**Issue by hjyoung1** [kiwibrowser/android#60] opened 2019-05-10 15:39 UTC
Because of  'FAIR' decision by Google we lost youtube background playback feature from kiwi browser. 
Here's very lite extension which restore that feature. 
Working perfectly. 
NOTE :- This Extension is ported by xda member [suppossess](https://forum.xda-developers.com/member.php?u=9916571)
I'm only sharing here. 

[youtube_background.zip](https://github.com/kiwibrowser/android/files/3167161/youtube_background.zip)

Just open extension setting (chrome://extensions) >>> activate developer mode >>> tap on load >>> select youtube_background.zip
And you're done. Enjoy youtube bg playback experience :)

**Comment by RavetcoFX** [comment] 2019-05-14 23:02
I wonder if an f-droid version of the app could have it enabled?

**Comment by hjyoung1** [comment] 2019-05-15 21:29
I don't see f-droid version happening anytime soon. Because fdroid only approves fully open source apps.
Kiwi browser is one of the best but sources are incomplete.

**Comment by premkumarmahenderker** [comment] 2020-05-12 07:32
Even if it's against the youtube policy, I'll definitely recommend this extension as it's an open source implementation of chromium API extension.

**Comment by premkumarmahenderker** [comment] 2020-05-12 07:33
Even if it's against the youtube policy, I'll definitely recommend this extension as it's an open source implementation of chromium API extension.

**Comment by slavru** [comment] 2020-08-15 21:29
An some incredible com herr

Ohhhhhh ye
Titans falls

**Comment by pierro78** [comment] 2021-04-19 00:38
thanks ! 

at first it didn't work for me but I just needed to exit and restart kiwi ;)

PS :
a "funny" thing is that I don't need this extension in LineageOS 17.1 to play youtube videos in the background with Kiwi Browser ;)

**Comment by ballo** [comment] 2021-06-25 04:55
Will the kiwi sources be open sometime? I also use fdroid

**Comment by Delphox** [comment] 2021-07-13 18:47
Zip extensions have the problem of getting wiped when you clear cache, so I packed it as a CRX for permanent install (also changed the icon color kiwi color-ish youtube icon). [Download it here!
](https://cdn.discordapp.com/attachments/493934106816544790/868305377165447188/youtube_background.crx)

**Comment by KaKi87** [comment] 2021-07-23 15:04
Duplicate of #58

**Closed by KaKi87** 2021-07-23 15:04 UTC

**Comment by adityaswaminathan** [comment] 2022-01-16 18:48
Hey, I use the read aloud extension to read out articles. However it stops playing if i close kiwi or turn the screen off. Is there a solution for this? Thanks

**Comment by iam0day** [comment] 2022-03-17 12:18
> Because of 'FAIR' decision by Google we lost youtube background playback feature from kiwi browser. Here's very lite extension which restore that feature. Working perfectly. NOTE :- This Extension is ported by xda member [suppossess](https://forum.xda-developers.com/member.php?u=9916571) I'm only sharing here.
> 
> [youtube_background.zip](https://github.com/kiwibrowser/android/files/3167161/youtube_background.zip)
> 
> Just open extension setting (chrome://extensions) >>> activate developer mode >>> tap on load >>> select youtube_background.zip And you're done. Enjoy youtube bg playback experience :)

Hi, i took the liberty to update the manifest to version 3: [youtube_background.zip](https://github.com/kiwibrowser/android/files/8285190/youtube_background.zip)

**Comment by ghost** [comment] 2022-03-17 13:09
Kiwi supports extensions, so you can test if [violentmonkey](https://violentmonkey.github.io/) extension fixes that. I haven't checked it yet, but in short you should
1. install extension https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag
2. visit Youtube in the Kiwi Browser
3. click the violentmonkey extension icon
4. click "Find the script for this site"
5. Search for background Youtube or something like that.. e.g https://greasyfork.org/en/scripts/437123-youtube-background-playback-kiwi-browser
6. test background play


Also there are alternatives, like https://violentmonkey.github.io/#alternatives

**Comment by muhamedkarajic** [comment] 2022-04-28 03:21
Thanks :)

**Comment by soymadip** [comment] 2022-07-09 18:29
Does this extension only work for YouTube or it enables background playback for other sites also?

**Comment by iam0day** [comment] 2022-07-10 13:47
> Does this extension only work for YouTube or it enables background playback for other sites also?

Hello, the code is intended for background playback of videos and music from YouTube.

**Comment by soymadip** [comment] 2022-07-13 06:02
> > Does this extension only work for YouTube or it enables background playback for other sites also?
> 
> Hello, the code is intended for background playback of videos and music from YouTube.

Ow, ok

**Comment by muhamedkarajic** [comment] 2022-09-11 13:26
> Zip extensions have the problem of getting wiped when you clear cache, so I packed it as a CRX for permanent install (also changed the icon color kiwi color-ish youtube icon). [Download it here! ](https://cdn.discordapp.com/attachments/493934106816544790/868305377165447188/youtube_background.crx)

This one worked for me. Thank you.

**Comment by zpunout** [comment] 2022-09-15 04:28
I noticed that this background playback extension in Kiwi Browser works for YouTube if I disable battery optimization, otherwise playback stops after a few minutes. However, I tested playback in other websites such as Brighteon and SeeTvNetwork and playback still halts after a few minutes. Is it easy for me to learn how to modify the extension to include other websites?

**Comment by bremaya** [comment] 2022-10-06 19:15
You can use this extension to view the video in PIP mode:

https://chrome.google.com/webstore/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg

**Comment by CrazyWolf13** [comment] 2023-01-05 07:18
> Kiwi supports extensions, so you can test if [violentmonkey](https://violentmonkey.github.io/) extension fixes that. I haven't checked it yet, but in short you should
> 1. install extension https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag
> 2. visit Youtube in the Kiwi Browser
> 3. click the violentmonkey extension icon
> 4. click "Find the script for this site"
> 5. Search for background Youtube or something like that.. e.g https://greasyfork.org/en/scripts/437123-youtube-background-playback-kiwi-browser
> 6. test background play
> 
> 
> Also there are alternatives, like https://violentmonkey.github.io/#alternatives

This is insane thank you for sharing this <3

**Comment by ll0r3nt3** [comment] 2023-06-20 15:45
> Zip extensions have the problem of getting wiped when you clear cache, so I packed it as a CRX for permanent install (also changed the icon color kiwi color-ish youtube icon). [Download it here! ](https://cdn.discordapp.com/attachments/493934106816544790/868305377165447188/youtube_background.crx)

Maybe update CRX whit this? manifest v3 https://github.com/kiwibrowser/android/files/8285190/youtube_background.zip

Thx

**Comment by ilhan-athn7** [comment] 2023-07-29 19:13
I have switched to kiwi browser from firefox, and youtube was my biggest pain to keep me using kiwi.

Thanks for the module, it is working perfectly 🤞

**Comment by shahul01** [comment] 2023-09-15 04:29
@hjyoung1 hey dude, thanks for sharing this extension!!

**Comment by CrazyWolf13** [comment] 2023-09-15 04:32
To everyone here check out revanced manager, you can download on github and patch the original youtube/youtube music app to get premium functions, ad free background playback and so on, much better than outdated kiwi

**Comment by ilhan-athn7** [comment] 2023-09-15 05:37
> To everyone here check out revanced manager, you can download on github and patch the original youtube/youtube music app to get premium functions, ad free background playback and so on, much better than outdated kiwi

We are totally aware about Youtube Vanced/Revanced etc
Some of us just don't want to use apps that are able to run on web browsers like instagram, discord and youtube.

**Comment by brokedarius** [comment] 2023-09-16 17:21
the userscript you really want for background playback to work on all sites is one called video background play fix

[https://greasyfork.org/en/scripts/371641-video-background-play-fix](url)

That coupled with simple youtube age restriction bypass and ublock origin is all you need. No more vanced, newpipe etc, I think there's just too many attempts to turn into an app what just needs to be a website.

**Comment by soymadip** [comment] 2023-09-16 17:34
> That coupled with simple youtube age restriction bypass and ublock origin is all you need. No more vanced, newpipe etc, I think there's just too many attempts to turn into an app what just needs to be a website.

Except Google is literally blocking adblockers in yt website.......

**Comment by alkisqwe** [comment] 2024-04-12 17:26
I Created An Extension For This As Well Based On Firefox Video Background Play Fix Extension
https://github.com/alkisqwe/Youtube-Background

**Comment by akchaudhary6532** [comment] 2024-12-08 19:43
> I Created An Extension For This As Well Based On Firefox Video Background Play Fix Extension https://github.com/alkisqwe/Youtube-Background

This works for iOS as well with Safari and Hyperweb. Just install Hyperweb and use the content.js link to install the script. Now simply play a video on Safari, minimise and enjoy. It works when the screen is off as well.

The only issue is that it doesn't play the next song due to Safari safety measure of background page redirect.
